[features]
seeds = false
[programs.localnet]
mysolanaapp = "2r78ZhLbrEckmrENcwMWDKKwR3kw6nLf7U8PU3UZQfjL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/david/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
