[features]
seeds = false
[programs.localnet]
mysolanaapp = "6FFmFrZMQxH3DB2VGwVaAR13tEgvmfyHVwhMVooot9VG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/david/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
